### ISSUE TITLE
Android and ios app creshing in release 

### ISSUE THREAD

**Issue by rushi08** [stefalda/ReactNativeLocalization#222]
Android and ios app creshing in release

**Comment by JCYDigitalinnov** [comment]
Same issue. I got this error in android 

```
com.facebook.react.common.JavascriptException: Error: Requiring unknown module "./locale/mylocale"., js engine: hermes, stack:
unknownModuleError@1:68612
loadModuleImplementation@1:68421
guardedLoadModule@1:68018
metroRequire@1:67689
loadLocale@1:1027672
updateLocale@1:1028382
?anon0@1:972790
asyncGeneratorStep@1:75357
_next@1:75629
tryCallOne@53:15
anonymous@139:26
anonymous@1:200493
_callTimer@1:199439
_callReactNativeMicrotasksPass@1:199604
callReactNativeMicrotasks@1:201592
callReactNativeMicrotasks@1:102837
anonymous@1:101928
guard@1:102678
flushedQueue@1:101839
invokeCallbackAndReturnFlushedQueue@1:101782

    at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
    at com.facebook.jni.NativeRunnable.run(Native Method)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:299)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
    at java.lang.Thread.run(Thread.java:1012)
```

**Comment by JCYDigitalinnov** [comment]
I got it working now.

Just delete `node_modules` then `yarn install` or `npm install` 

Then build release your apk now
